/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_preferences (void);
GtkWidget* create_dialog_network_settings (void);
GtkWidget* create_dialog_server_settings (void);
GtkWidget* create_dialog_channel_settings (void);
GtkWidget* create_dialog_ignore_settings (void);
GtkWidget* create_dialog_highlight_settings (void);
